### PR TITLE
added deleted dupicated bits :)

### PR DESCRIPTION
**Pull request by MCPEGamerJPatGitHub**

### CODE REVIEW

**Comment by DunxGit** [comment]
It's a bloomin serch page you ediot

**Comment by MCPEGamerJPatGitHub** [comment]
You say I'm a idiot? I'm just pointing out that there is two code pages with the same html code. There's no point to do that :)

**Comment by DunxGit** [comment]
i dont care

**Comment by MCPEGamerJPatGitHub** [comment]
Loooool

**Comment by MCPEGamerJPatGitHub** [comment]
I can't interfere with GITHUB :P

**Pull request closed without merging**
